### ISSUE TITLE
Error: BrowserModule has already been loaded

### ISSUE THREAD

**Issue by mastropinguino** [xtianus79/multiple-date-picker-a2#3]
Hi,
I'm trying to use the plugin in my new Angular2 app.
I installed plugin in the usual way (npm install multiple-date-picker-a2 --save).
In the template i put simply:

```html
<multiple-date-picker></multiple-date-picker>
````

When page is rendered the browser give up:

```
ERROR Error: Uncaught (in promise): Error: BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead.
Error: BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead.
    at new BrowserModule (platform-browser.es5.js:4179)
    at FooModuleInjector.createInternal (module.ngfactory.js [sm]:1)
    at FooModuleInjector.NgModuleInjector.create (core.es5.js:3537)
    at NgModuleFactory.create (core.es5.js:3510)
    at MapSubscriber.project (router.es5.js:3320)
...
```

The page being rendered is inside a module "FooModule" and I suppose that this is the problem.
In fact when I use the plugin in a component declared in the AppModule all things goes right.

I notice that you include [BrowserModule @ line 8](https://github.com/xtianus79/multiple-date-picker-a2/blob/master/src/multiple-date-picker.module.ts#L8), and this seems to be the issue. The angular2 doc suggest to not use BrowserModule directly, instead use CommonModule.

In my try I change the include from BrowserModule  to CommonModule and component works again.

I make changes in my repo, so I'm creating a PR for that.
Please if you merge my PR give a build to project because I can't make the compiled "dist" files because my typescript compiler blame about strange errors.

Regards

**Comment by xtianus79** [comment]
You haven't put any parameters in... 

<multiple-date-picker
      [showDaysOfSurroundingMonths]="false"
      [disallowBackPastMonths]="true"
      [sundayFirstDay]="true"
      [matIcons]="true"
      disableDaysBefore="true"
     [(ngModel)]="selectedDays"
>
</multiple-date-picker>

**Comment by xtianus79** [comment]
update coming later today... let me know if you have the same issue.

**Comment by iwoogy** [comment]
I still have the same issue with the latest version 3.0.0.

I've changed the transpiled js multiple-date-picker.module.js according to @mastropinguino recommendations.

var common_1 = require("@angular/common");
imports: [ common_1.CommonModule, forms_1.FormsModule ],

instead of the BrowserModule declaration.

Could you change the code ?

Thanks

Bobby

**Comment by lenderby** [comment]
I too am still having the same issue. Thanks for the fix Bobby.

**Comment by barrct** [comment]
Issue still exists, exact same patch as @iwoogy

**Comment by linksach3** [comment]
This issue still exists. We are facing it when tried to lazy load the module where this is included. Is a fix expected soon?

**Comment by barrct** [comment]
Still buggy
Lines to fix
https://github.com/xtianus79/multiple-date-picker-angular/blob/44fe897beeb367a5a6b02e4136e22095a55c9767/dist/multiple-date-picker.module.js#L4
and
https://github.com/xtianus79/multiple-date-picker-angular/blob/44fe897beeb367a5a6b02e4136e22095a55c9767/dist/multiple-date-picker.module.js#L14

var platform_browser_1 = require("@angular/platform-browser");
to
var platform_browser_1 = require("@angular/common");

and
                        platform_browser_1.BrowserModule,
to
                        platform_browser_1.CommonModule,

Looks like the bug was introduced 3 years ago and the source has been fixed in 2019 but it seems that it has not been recompiled so a basic package.json doesn't get the fix.

**Comment by xtianus79** [comment]
ok I have a plan I am going to rip this apart and redo this in the properly app component way with Angular 9 as a baseline.  I will do this this weekend.  Everything should be working after that.

**Comment by evandersar** [comment]
still not working
